### ISSUE TITLE
Topic to table Multiplexing no supported

### ISSUE THREAD

**Issue by mailmahee** [scylladb/kafka-connect-scylladb#9]
**Issue:** 
Currently, we create the table in Scylla automatically with the same name as the topic in Kafka. If the table is already created with the corresponding name then we simply use it. One request that came in from a customer is that - if we want to use the data in a topic and store the content into multiple tables, it is not currently possible. Even though this is a not-so-common feature request - I am adding this so I can track the issues.

**Comment by dkropachev** [comment]
If you consumed a message from kafka and have two tables/clusters to write it to, there is a problem with error handling.
Consider following scenario:
1. Connector writes record to a Table A successfully
2. But it fails to do that for Table B.

Now Table A and B are not in sync, and you also have to either commit  offset or retry on the message, but:
1. If you commit then table B will never get record from the message
2. if you retry then table A is going to stuck because you can't read new messages from kafka since offset has not been changed. 

Now, there are different cases, you can either ignore error on either table if other succeeds, or you fail if query to any table fails.
What if you have three tables or more.

To not to go into these scenarios we prefer not to have this functionality, but rather to advise to run multiple kafka connectors targeting different tables.
